##FROM nginx:1.13.3-alpine

#### Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

#### From 'builder' stage copy over the artifacts in dist folder to default nginx public folder
##COPY /dist /usr/share/nginx/html

##ENV LISTEN_PORT=80

##EXPOSE 80

##CMD ["nginx", "-g", "daemon off;"]


FROM node:7 as build
WORKDIR /mongoLogUi

COPY package.json /mongoLogUi
RUN npm install -g @angular/cli
RUN npm install
RUN npm run ng build -prod

COPY . /mongoLogUi

FROM alpine:3.4 as deploy

COPY --from=build /mongoLogUi/dist/ /dist/

ENV LISTEN_PORT=80

EXPOSE 80
