##FROM nginx:1.13.3-alpine

#### Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

#### From 'builder' stage copy over the artifacts in dist folder to default nginx public folder
##COPY /dist /usr/share/nginx/html

##ENV LISTEN_PORT=80

##EXPOSE 80

##CMD ["nginx", "-g", "daemon off;"]

FROM node:9.6.1

RUN mkdir /usr/src/angularapp
WORKDIR /usr/src/angularapp

ENV PATH /usr/src/angularapp/node_modules/.bin:$PATH

COPY package.json /usr/src/angularapp/package.json
RUN npm install
RUN npm install -g @angular/cli@1.7.1

COPY . /usr/src/angularapp

CMD ng serve --host 0.0.0.0
