##FROM nginx:1.13.3-alpine

#### Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

#### From 'builder' stage copy over the artifacts in dist folder to default nginx public folder
##COPY /dist /usr/share/nginx/html

##ENV LISTEN_PORT=80

##EXPOSE 80

##CMD ["nginx", "-g", "daemon off;"]

FROM node:alpine

RUN mkdir -p /usr/src/mongoLogUi
WORKDIR /usr/src/mongoLogUi
RUN npm install -g http-server

COPY . /usr/src/mongoLogUi

RUN npm install -g @angular/cli

COPY package.json /usr/src/mongoLogUi/

RUN npm install

CMD [ "ng", "build" ]

EXPOSE 4200

CMD ["cd", "/usr/src/mongoLogUi/dist", "http-server" ,"-p", "4200"]
